%YAML 1.2
---
# name of the training project
name: 'example'

dataset: 
    # newest nof chunks to parse
    num_chunks: 120000
    # trainingset ratio
    train_ratio: 0.90
    # For separated test and train data.
    input_train: '/path/to/chunks/*/train/' # supports glob
    input_test: '/path/to/chunks/*/test/' # supports glob
    # For a one-shot run with all data in one directory.
    # input: '/path/to/chunks/*/draw/' # supports glob

training:
    # gpu ids to train on
    gpus:                              
        - 0
        - 1
    # enable/disable stochastic weight averaging
    swa: true
    # training batch size
    batch_size: 4096
    # batchsize that fits in gpu memory, must be a multiple of batch_size
    vram_batch_size: 512               
    # eval test set values after this many steps
    test_steps: 2000                   
    # training reports its average values after this many steps.
    info_steps: 200
    # terminate after these steps
    total_steps: 10000
    # optional frequency for checkpointing before finish
    checkpoint_steps: 2500
    # size of the shuffle buffer
    shuffle_size: 100000
    # list of learning rates
    lr_values:
        - 0.2
        - 0.02
    # list of boundaries
    lr_boundaries:
        - 5000
    # weight of policy loss
    policy_loss_weight: 1.0
    # weight of value loss
    value_loss_weight: 1.0
    # network storage dir
    path: '/path/to/store/networks'

model:
    # filters per layer
    filters: 128
    # residual blocks in resnet
    residual_blocks: 10
...
